Added Basic UI
JacintaNgwu/OOP-school-library pull request #6
Opened 2023-03-17 10:28 UTC by JacintaNgwu

- Built an interactive console apps.

- Created an app.rb file that serves as a console app entry-point. It contains methods that do the following:
List all books.
List all people.
Create a person (teacher or student, not a plain Person).
Create a book.
Create a rental.
List all rentals for a given person id.

- Created main.rb file that defines the entry point, that is invoked at the end of the file. This method do the following:
Present the user with a list of options to perform.
Lets users choose an option.
If needed, ask for parameters for the option.
Have a way to quit the app.

**Below is a screenshot of the console**
![image](https://user-images.githubusercontent.com/100554236/225897282-bec16b5e-998e-4b1c-9005-0536fbe0f20c.png)
![image](https://user-images.githubusercontent.com/100554236/225897523-7db7ae63-25fe-472b-9030-043aa90e1728.png)

2023-03-17 12:19 UTC, AmaduKamara requested changes
# Status: Required Changes  ♻️ ♻️ ♻️

Hi @JacintaNgwu,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights:

✅ You used Gityflow correctly 👍🏽
✅ Linter checks passed 👍🏽
✅ Good descriptive PR 👍🏽

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-17 12:19 UTC, AmaduKamara commented on app.rb
> +  end
- [ ] When I try to display a rental for a person, the app crashes with the error in the screenshot below. Kindly fix that 👍🏽

<img width="1353" alt="Screenshot 2023-03-17 at 12 06 22 PM" src="https://user-images.githubusercontent.com/50941074/225900159-52d8c652-c634-4335-bc0d-e1c8abdda12e.png">

2023-03-17 12:19 UTC, AmaduKamara commented on app.rb
> +end
- [ ] Let's try not to disable Linter checks as they help us write clean and professional code. Disabling linter checks defies its purpose. Kindly fix the Linter error 👍🏽

2023-03-18 00:15 UTC, anagudelogu approved these changes
# STATUS: APPROVED! 🍾 🎆 🥇 

Hi @JacintaNgwu, 
I'm Andres.

You did a great job working on this milestone, your project is complete! 🚀 
There is nothing else to say other than... it's time to merge it 🤖  
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-18 09:12 UTC, merged